const mongoose = require('mongoose');
const asyncHandler = require('express-async-handler');
const Budget = require('../models/budgetModel');
const Transaction = require('../models/transactionModel');

const getBudgets = asyncHandler(async (req, res) => {
    const userId = new mongoose.Types.ObjectId(req.user.id);
    const now = new Date();
    const currentMonth = now.getMonth() + 1;
    const currentYear = now.getFullYear();

    // 1. Get user's budgets for the current month
    const existingBudgets = await Budget.find({
        user: userId,
        month: currentMonth,
        year: currentYear
    });

    // 2. Aggregate spending for the current month
    const currentSpending = await Transaction.aggregate([
        {
            $match: {
                user: userId,
                type: 'expense',
                isGroupExpense: false,
                date: {
                    $gte: new Date(currentYear, currentMonth - 1, 1),
                    $lt: new Date(currentYear, currentMonth, 1)
                }
            }
        },
        {
            $group: {
                _id: '$category',
                totalSpent: { $sum: '$amount' }
            }
        }
    ]);

    // 3. Historical analysis (last 6 months) for recommendations and auto-generation
    const sixMonthsAgo = new Date();
    sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);

    const historicalAnalysis = await Transaction.aggregate([
        {
            $match: {
                user: userId,
                type: 'expense',
                isGroupExpense: false,
                date: { $gte: sixMonthsAgo, $lt: new Date(currentYear, currentMonth - 1, 1) }
            }
        },
        {
            $group: {
                _id: {
                    category: '$category',
                    month: { $month: '$date' },
                    year: { $year: '$date' }
                },
                monthlyTotal: { $sum: '$amount' }
            }
        },
        {
            $group: {
                _id: '$_id.category',
                avgSpent: { $avg: '$monthlyTotal' },
                monthCount: { $count: {} }
            }
        }
    ]);

    // 4. Merge data and handle only explicitly set budgets
    const categories = ['Food', 'Transport', 'Shopping', 'Rent', 'Salary', 'Entertainment', 'Health', 'Other'];
    const finalBudgets = existingBudgets.map(budget => {
        const cat = budget.category;
        const spent = currentSpending.find(s => s._id === cat)?.totalSpent || 0;
        const history = historicalAnalysis.find(h => h._id === cat);
        const avgSpent = history ? Math.round(history.avgSpent) : 0;

        return {
            _id: budget._id,
            category: cat,
            limit: budget.amount || 0,
            spent,
            avgSpent,
            remaining: (budget.amount || 0) - spent,
            isAutoGenerated: false,
            hasHistory: !!history
        };
    });

    res.status(200).json(finalBudgets);
});

const setBudget = asyncHandler(async (req, res) => {
    const { category, amount } = req.body;

    if (!category || amount === undefined) {
        res.status(400);
        throw new Error('Please add category and amount');
    }

    const currentMonth = new Date().getMonth() + 1;
    const currentYear = new Date().getFullYear();

    const budget = await Budget.findOneAndUpdate(
        { user: req.user.id, category, month: currentMonth, year: currentYear },
        { amount: Number(amount) },
        { new: true, upsert: true }
    );
    res.status(200).json(budget);
});

const deleteBudget = asyncHandler(async (req, res) => {
    const budget = await Budget.findById(req.params.id);
    if (!budget) {
        res.status(404);
        throw new Error('Budget not found');
    }
    if (budget.user.toString() !== req.user.id) {
        res.status(401);
        throw new Error('Not authorized');
    }

    await budget.deleteOne();
    res.status(200).json({ id: req.params.id });
});

module.exports = {
    getBudgets,
    setBudget,
    deleteBudget
};
